// TypeScript definitions for Clip
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated

import { MisskeyClient } from './index';
import * as ComponentSchemas from './ComponentSchemas';

export interface PostClipsFavoriteRequest {
  clipId: string;
}

export type PostClipsFavoriteResponse = void;

export interface PostClipsUnfavoriteRequest {
  clipId: string;
}

export type PostClipsUnfavoriteResponse = void;

export interface ClipModule {
  /**
   * clips/favorite
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:clip-favorite*
   */
  postClipsFavorite(client: MisskeyClient, request: PostClipsFavoriteRequest): Promise<PostClipsFavoriteResponse>;
  /**
   * clips/unfavorite
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:clip-favorite*
   */
  postClipsUnfavorite(client: MisskeyClient, request: PostClipsUnfavoriteRequest): Promise<PostClipsUnfavoriteResponse>;
}

export const Clip: ClipModule;