// TypeScript definitions for Notes
// Generated by rescript-codegen-openapi
// DO NOT EDIT - This file is auto-generated

import { MisskeyClient } from './index';
import * as ComponentSchemas from './ComponentSchemas';

export interface PostChannelsTimelineRequest {
  channelId: string;
  limit?: number;
  sinceId?: string;
  untilId?: string;
  sinceDate?: number;
  untilDate?: number;
  allowPartial?: boolean;
  dimension?: unknown;
}

/**
 * OK (with results)
 */
export type PostChannelsTimelineResponse = ComponentSchemas.Note[];

export interface PostNotesRequest {
  local?: boolean;
  reply?: boolean;
  renote?: boolean;
  withFiles?: boolean;
  poll?: boolean;
  limit?: number;
  sinceId?: string;
  untilId?: string;
}

/**
 * OK (with results)
 */
export type PostNotesResponse = ComponentSchemas.Note[];

export interface PostNotesChildrenRequest {
  noteId: string;
  limit?: number;
  sinceId?: string;
  untilId?: string;
}

/**
 * OK (with results)
 */
export type PostNotesChildrenResponse = ComponentSchemas.Note[];

export interface PostNotesConversationRequest {
  noteId: string;
  limit?: number;
  offset?: number;
}

/**
 * OK (with results)
 */
export type PostNotesConversationResponse = ComponentSchemas.Note[];

export interface PostNotesCreateRequest {
  visibility?: string;
  visibleUserIds?: string[];
  cw?: unknown;
  localOnly?: boolean;
  dimension?: unknown;
  reactionAcceptance?: unknown;
  noExtractMentions?: boolean;
  noExtractHashtags?: boolean;
  noExtractEmojis?: boolean;
  replyId?: unknown;
  renoteId?: unknown;
  channelId?: unknown;
  lang?: unknown;
  text?: unknown;
  fileIds?: string[];
  mediaIds?: string[];
  poll?: unknown;
  scheduledAt?: unknown;
  noCreatedNote?: boolean;
}

/**
 * OK (with results)
 */
export interface PostNotesCreateResponse {
  createdNote: ComponentSchemas.Note;
}

export interface PostNotesDeleteRequest {
  noteId: string;
}

export type PostNotesDeleteResponse = void;

export interface PostNotesFavoritesCreateRequest {
  noteId: string;
}

export type PostNotesFavoritesCreateResponse = void;

export interface PostNotesFavoritesDeleteRequest {
  noteId: string;
}

export type PostNotesFavoritesDeleteResponse = void;

export interface GetNotesFeaturedRequest {
  limit?: number;
  untilId?: string;
  channelId?: unknown;
}

/**
 * OK (with results)
 */
export type GetNotesFeaturedResponse = ComponentSchemas.Note[];

export interface PostNotesFeaturedRequest {
  limit?: number;
  untilId?: string;
  channelId?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesFeaturedResponse = ComponentSchemas.Note[];

export interface PostNotesGlobalTimelineRequest {
  withFiles?: boolean;
  withRenotes?: boolean;
  limit?: number;
  sinceId?: string;
  untilId?: string;
  sinceDate?: number;
  untilDate?: number;
  dimension?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesGlobalTimelineResponse = ComponentSchemas.Note[];

export interface PostNotesHybridTimelineRequest {
  limit?: number;
  sinceId?: string;
  untilId?: string;
  sinceDate?: number;
  untilDate?: number;
  allowPartial?: boolean;
  includeMyRenotes?: boolean;
  includeRenotedMyNotes?: boolean;
  includeLocalRenotes?: boolean;
  withFiles?: boolean;
  withRenotes?: boolean;
  withReplies?: boolean;
  dimension?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesHybridTimelineResponse = ComponentSchemas.Note[];

export interface PostNotesLocalTimelineRequest {
  withFiles?: boolean;
  withRenotes?: boolean;
  withReplies?: boolean;
  limit?: number;
  sinceId?: string;
  untilId?: string;
  allowPartial?: boolean;
  sinceDate?: number;
  untilDate?: number;
  dimension?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesLocalTimelineResponse = ComponentSchemas.Note[];

export interface PostNotesMentionsRequest {
  following?: boolean;
  limit?: number;
  sinceId?: string;
  untilId?: string;
  visibility?: string;
}

/**
 * OK (with results)
 */
export type PostNotesMentionsResponse = ComponentSchemas.Note[];

export interface PostNotesPollsRecommendationRequest {
  limit?: number;
  offset?: number;
  excludeChannels?: boolean;
}

/**
 * OK (with results)
 */
export type PostNotesPollsRecommendationResponse = ComponentSchemas.Note[];

export interface PostNotesPollsVoteRequest {
  noteId: string;
  choice: number;
}

export type PostNotesPollsVoteResponse = void;

export interface GetNotesReactionsRequest {
  noteId: string;
  type?: unknown;
  limit?: number;
  sinceId?: string;
  untilId?: string;
}

/**
 * OK (with results)
 */
export type GetNotesReactionsResponse = ComponentSchemas.NoteReaction[];

export interface PostNotesReactionsRequest {
  noteId: string;
  type?: unknown;
  limit?: number;
  sinceId?: string;
  untilId?: string;
}

/**
 * OK (with results)
 */
export type PostNotesReactionsResponse = ComponentSchemas.NoteReaction[];

export interface PostNotesRenotesRequest {
  noteId: string;
  limit?: number;
  sinceId?: string;
  untilId?: string;
}

/**
 * OK (with results)
 */
export type PostNotesRenotesResponse = ComponentSchemas.Note[];

export interface PostNotesRepliesRequest {
  noteId: string;
  sinceId?: string;
  untilId?: string;
  limit?: number;
}

/**
 * OK (with results)
 */
export type PostNotesRepliesResponse = ComponentSchemas.Note[];

export interface PostNotesScheduledCancelRequest {
  draftId: string;
}

export type PostNotesScheduledCancelResponse = void;

export interface PostNotesScheduledListRequest {
  limit?: number;
  offset?: number;
}

/**
 * OK (with results)
 */
export type PostNotesScheduledListResponse = ComponentSchemas.NoteDraft[];

export interface PostNotesSearchRequest {
  query: string;
  sinceId?: string;
  untilId?: string;
  limit?: number;
  offset?: number;
  host?: string;
  userId?: unknown;
  channelId?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesSearchResponse = ComponentSchemas.Note[];

export interface PostNotesSearchByTagRequest {
  local?: unknown;
  reply?: unknown;
  renote?: unknown;
  withFiles?: boolean;
  poll?: unknown;
  sinceId?: string;
  untilId?: string;
  limit?: number;
  tag?: string;
  query?: string[][];
}

/**
 * OK (with results)
 */
export type PostNotesSearchByTagResponse = ComponentSchemas.Note[];

export interface PostNotesShowRequest {
  noteId: string;
}

/**
 * OK (with results)
 */
export type PostNotesShowResponse = ComponentSchemas.Note;

export interface PostNotesStateRequest {
  noteId: string;
}

/**
 * OK (with results)
 */
export interface PostNotesStateResponse {
  isFavorited: boolean;
  isMutedThread: boolean;
}

export interface PostNotesThreadMutingCreateRequest {
  noteId: string;
}

export type PostNotesThreadMutingCreateResponse = void;

export interface PostNotesThreadMutingDeleteRequest {
  noteId: string;
}

export type PostNotesThreadMutingDeleteResponse = void;

export interface PostNotesTimelineRequest {
  limit?: number;
  sinceId?: string;
  untilId?: string;
  sinceDate?: number;
  untilDate?: number;
  allowPartial?: boolean;
  includeMyRenotes?: boolean;
  includeRenotedMyNotes?: boolean;
  includeLocalRenotes?: boolean;
  withFiles?: boolean;
  withRenotes?: boolean;
  dimension?: unknown;
}

/**
 * OK (with results)
 */
export type PostNotesTimelineResponse = ComponentSchemas.Note[];

export interface PostNotesTranslateRequest {
  noteId: string;
  targetLang: string;
}

/**
 * OK (with results)
 */
export interface PostNotesTranslateResponse {
  sourceLang: string;
  text: string;
}

export interface PostNotesUnrenoteRequest {
  noteId: string;
}

export type PostNotesUnrenoteResponse = void;

export interface PostNotesUserListTimelineRequest {
  listId: string;
  limit?: number;
  sinceId?: string;
  untilId?: string;
  sinceDate?: number;
  untilDate?: number;
  allowPartial?: boolean;
  includeMyRenotes?: boolean;
  includeRenotedMyNotes?: boolean;
  includeLocalRenotes?: boolean;
  withRenotes?: boolean;
  withFiles?: boolean;
}

/**
 * OK (with results)
 */
export type PostNotesUserListTimelineResponse = ComponentSchemas.Note[];

export interface PostPromoReadRequest {
  noteId: string;
}

export type PostPromoReadResponse = void;

export interface GetUsersFeaturedNotesRequest {
  limit?: number;
  untilId?: string;
  userId: string;
}

/**
 * OK (with results)
 */
export type GetUsersFeaturedNotesResponse = ComponentSchemas.Note[];

export interface PostUsersFeaturedNotesRequest {
  limit?: number;
  untilId?: string;
  userId: string;
}

/**
 * OK (with results)
 */
export type PostUsersFeaturedNotesResponse = ComponentSchemas.Note[];

export interface NotesModule {
  /**
   * channels/timeline
   * No description provided.

**Credential required**: *No*
   */
  postChannelsTimeline(client: MisskeyClient, request: PostChannelsTimelineRequest): Promise<PostChannelsTimelineResponse>;
  /**
   * notes
   * No description provided.

**Credential required**: *No*
   */
  postNotes(client: MisskeyClient, request: PostNotesRequest): Promise<PostNotesResponse>;
  /**
   * notes/children
   * No description provided.

**Credential required**: *No*
   */
  postNotesChildren(client: MisskeyClient, request: PostNotesChildrenRequest): Promise<PostNotesChildrenResponse>;
  /**
   * notes/conversation
   * No description provided.

**Credential required**: *No*
   */
  postNotesConversation(client: MisskeyClient, request: PostNotesConversationRequest): Promise<PostNotesConversationResponse>;
  /**
   * notes/create
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:notes*
   */
  postNotesCreate(client: MisskeyClient, request: PostNotesCreateRequest): Promise<PostNotesCreateResponse>;
  /**
   * notes/delete
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:notes*
   */
  postNotesDelete(client: MisskeyClient, request: PostNotesDeleteRequest): Promise<PostNotesDeleteResponse>;
  /**
   * notes/favorites/create
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:favorites*
   */
  postNotesFavoritesCreate(client: MisskeyClient, request: PostNotesFavoritesCreateRequest): Promise<PostNotesFavoritesCreateResponse>;
  /**
   * notes/favorites/delete
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:favorites*
   */
  postNotesFavoritesDelete(client: MisskeyClient, request: PostNotesFavoritesDeleteRequest): Promise<PostNotesFavoritesDeleteResponse>;
  /**
   * notes/featured
   * No description provided.

**Credential required**: *No*
   */
  getNotesFeatured(client: MisskeyClient, request: GetNotesFeaturedRequest): Promise<GetNotesFeaturedResponse>;
  /**
   * notes/featured
   * No description provided.

**Credential required**: *No*
   */
  postNotesFeatured(client: MisskeyClient, request: PostNotesFeaturedRequest): Promise<PostNotesFeaturedResponse>;
  /**
   * notes/global-timeline
   * No description provided.

**Credential required**: *No*
   */
  postNotesGlobalTimeline(client: MisskeyClient, request: PostNotesGlobalTimelineRequest): Promise<PostNotesGlobalTimelineResponse>;
  /**
   * notes/hybrid-timeline
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesHybridTimeline(client: MisskeyClient, request: PostNotesHybridTimelineRequest): Promise<PostNotesHybridTimelineResponse>;
  /**
   * notes/local-timeline
   * No description provided.

**Credential required**: *No*
   */
  postNotesLocalTimeline(client: MisskeyClient, request: PostNotesLocalTimelineRequest): Promise<PostNotesLocalTimelineResponse>;
  /**
   * notes/mentions
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesMentions(client: MisskeyClient, request: PostNotesMentionsRequest): Promise<PostNotesMentionsResponse>;
  /**
   * notes/polls/recommendation
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesPollsRecommendation(client: MisskeyClient, request: PostNotesPollsRecommendationRequest): Promise<PostNotesPollsRecommendationResponse>;
  /**
   * notes/polls/vote
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:votes*
   */
  postNotesPollsVote(client: MisskeyClient, request: PostNotesPollsVoteRequest): Promise<PostNotesPollsVoteResponse>;
  /**
   * notes/reactions
   * No description provided.

**Credential required**: *No*
   */
  getNotesReactions(client: MisskeyClient, request: GetNotesReactionsRequest): Promise<GetNotesReactionsResponse>;
  /**
   * notes/reactions
   * No description provided.

**Credential required**: *No*
   */
  postNotesReactions(client: MisskeyClient, request: PostNotesReactionsRequest): Promise<PostNotesReactionsResponse>;
  /**
   * notes/renotes
   * No description provided.

**Credential required**: *No*
   */
  postNotesRenotes(client: MisskeyClient, request: PostNotesRenotesRequest): Promise<PostNotesRenotesResponse>;
  /**
   * notes/replies
   * No description provided.

**Credential required**: *No*
   */
  postNotesReplies(client: MisskeyClient, request: PostNotesRepliesRequest): Promise<PostNotesRepliesResponse>;
  /**
   * notes/scheduled/cancel
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:notes*
   */
  postNotesScheduledCancel(client: MisskeyClient, request: PostNotesScheduledCancelRequest): Promise<PostNotesScheduledCancelResponse>;
  /**
   * notes/scheduled/list
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:notes*
   */
  postNotesScheduledList(client: MisskeyClient, request: PostNotesScheduledListRequest): Promise<PostNotesScheduledListResponse>;
  /**
   * notes/search
   * No description provided.

**Credential required**: *No*
   */
  postNotesSearch(client: MisskeyClient, request: PostNotesSearchRequest): Promise<PostNotesSearchResponse>;
  /**
   * notes/search-by-tag
   * No description provided.

**Credential required**: *No*
   */
  postNotesSearchByTag(client: MisskeyClient, request: PostNotesSearchByTagRequest): Promise<PostNotesSearchByTagResponse>;
  /**
   * notes/show
   * No description provided.

**Credential required**: *No*
   */
  postNotesShow(client: MisskeyClient, request: PostNotesShowRequest): Promise<PostNotesShowResponse>;
  /**
   * notes/state
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesState(client: MisskeyClient, request: PostNotesStateRequest): Promise<PostNotesStateResponse>;
  /**
   * notes/thread-muting/create
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:account*
   */
  postNotesThreadMutingCreate(client: MisskeyClient, request: PostNotesThreadMutingCreateRequest): Promise<PostNotesThreadMutingCreateResponse>;
  /**
   * notes/thread-muting/delete
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:account*
   */
  postNotesThreadMutingDelete(client: MisskeyClient, request: PostNotesThreadMutingDeleteRequest): Promise<PostNotesThreadMutingDeleteResponse>;
  /**
   * notes/timeline
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesTimeline(client: MisskeyClient, request: PostNotesTimelineRequest): Promise<PostNotesTimelineResponse>;
  /**
   * notes/translate
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesTranslate(client: MisskeyClient, request: PostNotesTranslateRequest): Promise<PostNotesTranslateResponse>;
  /**
   * notes/unrenote
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:notes*
   */
  postNotesUnrenote(client: MisskeyClient, request: PostNotesUnrenoteRequest): Promise<PostNotesUnrenoteResponse>;
  /**
   * notes/user-list-timeline
   * No description provided.

**Credential required**: *Yes* / **Permission**: *read:account*
   */
  postNotesUserListTimeline(client: MisskeyClient, request: PostNotesUserListTimelineRequest): Promise<PostNotesUserListTimelineResponse>;
  /**
   * promo/read
   * No description provided.

**Credential required**: *Yes* / **Permission**: *write:account*
   */
  postPromoRead(client: MisskeyClient, request: PostPromoReadRequest): Promise<PostPromoReadResponse>;
  /**
   * users/featured-notes
   * No description provided.

**Credential required**: *No*
   */
  getUsersFeaturedNotes(client: MisskeyClient, request: GetUsersFeaturedNotesRequest): Promise<GetUsersFeaturedNotesResponse>;
  /**
   * users/featured-notes
   * No description provided.

**Credential required**: *No*
   */
  postUsersFeaturedNotes(client: MisskeyClient, request: PostUsersFeaturedNotesRequest): Promise<PostUsersFeaturedNotesResponse>;
}

export const Notes: NotesModule;